In [ ]:
#float to int
x=4.98
print(x)
type(x)

4.98


float

In [ ]:
y=int(x)
print(y)
type(y)

4


int

In [ ]:
my_str = "programming"
print(my_str[1:4])


rog


In [ ]:
my_str="programming"
print(my_str[0:10:2])


pormi


In [ ]:
a=int(input("enter the d=first number"))
b=int(input("enter the second number"))

if(a>b):
  print("a is greater")
else:
  print("b is greater")

enter the d=first number2
enter the second number123
b is greater


In [ ]:
for i in range(5):
  lp=int(input("enter the price of laptop :->"))


enter the price of laptop :->10000
enter the price of laptop :->20000
enter the price of laptop :->30000
enter the price of laptop :->40000
enter the price of laptop :->50000


In [ ]:
number = (1,2,3,4,5)
for i in number:
  print(i)

1
2
3
4
5


In [ ]:
n=int(input("enter the number"))

fact=1

if fact == 0:
  print("fact of 0 is 1")
else:
  for i in range(1,n+1):
    fact=fact*i
print(fact)


enter the number5
120


In [ ]:
def fac_val(n):
  fac = 1

  if fac == 0:
    return fac
  else:
    for i in range(1,n+1):
      fac=fac*i
  return fac

In [ ]:
print(fac_val(5))

120


use of numpy


In [21]:
import numpy as np


NUMPY ARRAY

In [22]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [25]:
#2d array
np_arr=np.array([(1,2,3,4,5),(6,7,8,9,10)])
print(np_arr)
type(np_arr)
np_arr.shape # 2 rows and  5 columns


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

In [26]:
#create np array of zeros
b=np.zeros((2,5))
print(b)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [27]:
#np arrays of all ones
c=np.ones((3,6))
print(c)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [28]:
#np array with a specific value
d=np.full((5,4),3)
print(d)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]
